modules/carAds/controllers/DefaultController.php
<?php

namespace app\modules\carAds\controllers;

use app\modules\carAds\models\Auto;
use yii\data\Pagination;
use yii\web\Controller;

/**
 * Default controller for the `carAds` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $models = Auto::find();
        $countModel = clone $models;

        $pages = new Pagination([
            'totalCount' => $countModel->count(),
            'pageSize' => 5,
            'defaultPageSize' => 5,
        ]);

        $ads = $models->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('index', [
            'ads' => $ads,
            'pages' => $pages,
        ]);
    }

    public function actionView($id)
    {
        $model = Auto::findOne($id);
        return $this->render('view', [
            'model' => $model
        ]);
    }
}

modules/carAds/views/default/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="carAds-default-index">
    <a class="btn btn-info" href="/carAds/brand">Brands</a>
    <a class="btn btn-info" href="/carAds/model">Models</a>
    <a class="btn btn-info" href="/carAds/equipment">Equipment</a>
    <?= Html::a('Create Auto', Url::to(['/carAds/auto/create']), ['class' => 'btn btn-success']) ?>
</div>

<div class="container">
    <?php foreach ($ads as $model) : ?>
        <div class="row ads-block">
            <div class="col-md-3 ">
                <?php
                $image = $model->getImages()->limit('1')->one();
                ?>
                <?= Html::img('@web/images/uploads/' . $image->image_146x106); ?>
            </div>
            <div class="col-md-3 v-center">
                <a href="<?php echo Url::toRoute(['default/view', 'id' => $model->id]) ?>"><?php echo $model->brands->name . ' ' . $model->models->name; ?></a>
            </div>
            <div class="col-md-3 v-center">
                <p><?php echo number_format($model->price, 0, '', ' '); ?> рублей</p>
            </div>
        </div>
        <a class="btn btn-danger delete-ads" data-id="<?php echo $model->id; ?>">Delete</a>
    <?php endforeach; ?>
</div>
<?php
    echo \yii\widgets\LinkPager::widget([
        'pagination' => $pages,
    ]);
?>

modules/carAds/views/default/view.php
<?php

use app\modules\carAds\models\UploadImage;
use yii\helpers\Html;

?>
<?php
$images = UploadImage::getImages($model);

foreach ($images as $img) {
    foreach ($img as $item) {

    }
}
?>
<div class="container">
    <div class="row block-view">
        <div class="col-md-8">
            <?php
            $img = $model->getImages()->limit('1')->one();
            ?>
            <?php echo Html::img('@web/images/uploads/' . $img->image_720x540); ?>
            <div class="block-mini-img">
                <?php
                $images = $model->getImages()->all();
                ?>
                <?php foreach ($images as $img) : ?>
                    <?php echo Html::img('@web/images/uploads/' . $img->image_146x106) ?>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="col-md-4">
            <h3><?php echo $model->brands->name . ' ' . $model->models->name ?></h3>
            <hr>
            <p><b>Пробег:</b> <?php echo number_format($model->mileage, 0, '', ' '); ?> км</p>
            <hr>
            <p><b>Дополнительное оборудование:</b></p>
            <ul>
                <?php foreach ($model->equipments as $item) : ?>
                    <li><?php echo $item->name; ?></li>
                <?php endforeach; ?>
            </ul>
            <hr>
            <p><b>Цена: </b><?php echo number_format($model->price, 0, '', ' ') ?> рублей</p>
            <hr>
            <p><b>Телефон: </b><?php echo $model->phone ?></p>
        </div>
    </div>
</div>